#!/usr/bin/env ruby
# -*- mode: ruby -*-

# An example use of the Ruby autograder

require './lib/auto_grader.rb'
require 'ruby-debug'

def grade(file,spec)
end

def usage
  STDERR.puts <<EndOfHelp
Usage: #{$0} submission_uri admin_user admin_password specfile.rb

Creates an autograder of the HerokuRspecGrader subclass (which evaluates
student code based solely on RSpec output) and grades the Heroku submission URI
with it.

EndOfHelp
  exit
end

usage() if (ARGV.length!=4 || ARGV[0] =~ /^-?-h/)
g = AutoGrader.create('5',
                      'HW5Grader',
                      ARGV[0],
                      {
                        :admin_user => ARGV[1],
                        :admin_pass => ARGV[2],
                        :spec => ARGV[3]
                      })
g.grade!
puts "Score out of 100: #{g.normalized_score(100)}\n"
puts "---BEGIN rspec comments---\n#{'-'*80}\n#{g.comments}\n#{'-'*80}\n---END rspec comments---"

# PFX = 'spec/fixtures'
# grade "#{PFX}/correct_example.rb", "#{PFX}/correct_example.spec.rb"
# grade "#{PFX}/example_with_syntax_error.rb", "#{PFX}/correct_example.spec.rb"
