#!/usr/bin/env ruby
require './lib/auto_grader'
require 'optparse'
load 'lib/graders/feature_grader.rb'

options = {:mt => true}
o = nil
OptionParser.new do |opts|
  o = opts
  opts.banner = "Usage: #{$0} [options] input.tar.gz description.yml"
  opts.on('-a', '--app PATH', 'Path to app') {|p| options[:app] = p}
  opts.on('-h', '--help', 'Display this screen') { puts opts; exit }
  opts.on('-m', '--[no-]multithread', 'Enable multithreading') { options[:mt] = true }
end.parse!

unless options[:app] and ARGV.count == 2
  puts o
  exit 1
end

d = Dir::getwd

begin
  ARGV.collect! {|p| File.expand_path p}
  Dir::chdir options.delete(:app)
  ENV["RAILS_ROOT"] = Dir::getwd
  options[:description] = ARGV[1]

  g = AutoGrader.create('3', 'HW3Grader', ARGV[0], options)
  g.grade!
  puts "Score out of 100: #{g.normalized_score(100)}\n"
  puts "---BEGIN cucumber comments---\n#{'-'*80}\n#{g.comments}\n#{'-'*80}\n---END cucumber comments---"
ensure
  Dir::chdir d
end
