#!/usr/bin/env ruby

require './lib/auto_grader_subprocess.rb'

unless ARGV.size == 3
  puts <<EOF
Usage: #{$0} submission spec grader_type
  submission and spec should be paths
  grader_type should be one of the classes in lib/graders/
EOF
  exit(-1)
end

submission_path = ARGV[0]
spec = ARGV[1]
grader_type = ARGV[2]

submission = File.open(submission_path, 'r'){|f| f.read}

score, comments = AutoGraderSubprocess.run_autograder_subprocess(submission, spec, grader_type)
puts "Score: #{score}/100"
puts comments
