# This does not support http URIs yet

# assign-1-part-1:
#   uri: http://s3.amazonaws.com/saasbook/assign1/part1_spec.rb
#   type: WeightedRspecGrader
# assign-1-part-2:
#   uri: http://s3.amazonaws.com/saasbook/assign1/part2_spec.rb
#   type: WeightedRspecGrader
# assign-1-part-3:
#   uri: http://s3.amazonaws.com/saasbook/assign1/part3_spec.rb
#   type: WeightedRspecGrader
# assign-1-part-4:
#   uri: http://s3.amazonaws.com/saasbook/assign1/part4_spec.rb
#   type: WeightedRspecGrader
# assign-1-part-5:
#   uri: http://s3.amazonaws.com/saasbook/assign1/part5_spec.rb
#   type: WeightedRspecGrader
# 
# assign-2-part-1:
#   uri: http://s3.amazonaws.com/saasbook/assign2/part1_spec.rb
#   type: WeightedRspecGrader
# assign-2-part-2:
#   uri: http://s3.amazonaws.com/saasbook/assign2/part2_spec.rb
#   type: WeightedRspecGrader
# assign-2-part-3:
#   uri: http://s3.amazonaws.com/saasbook/assign2/part3_spec.rb
#   type: HerokuRspecGrader
# assign-2-part-4:
#   uri: http://s3.amazonaws.com/saasbook/assign2/part4_spec.rb
#   type: HerokuRspecGrader
# assign-2-part-5:
#   uri: http://s3.amazonaws.com/saasbook/assign2/part5_spec.rb
#   type: HerokuRspecGrader

#assign-3-part-1:
#  uri: hw3.yml
#  type: HW3Grader

assign-4-part-1:
  uri: hw4.yml
  type: HW4Grader
